#include<stdio.h>
#include<signal.h>
#include<sys/types.h>
#include<unistd.h>
#include<stdlib.h> 
#include<string.h>
#include<sys/stat.h>
#include<fcntl.h>
#include<sys/shm.h>
#include<sys/ipc.h>
#include<sys/sem.h>
#include<time.h>
